# Generated by Django 2.2.1 on 2019-05-19 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_app', '0002_auto_20190519_1154'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='person',
            unique_together={('first_name', 'last_name')},
        ),
    ]
